# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS7DtBUch66qXmE8pZpesJXTvOcZlvBk
"""

import xgboost as xgb
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Carregar dados e treinar um modelo
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)

modelo = xgb.XGBClassifier()
modelo.fit(X_train, y_train)

# Salvar modelo treinado
modelo.save_model("modelo_xgb.bin")